# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "storage_backed_attributes"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dave Benvenuti"]
  s.date = "2012-11-15"
  s.description = "Allows models to add attributes which have content backed by s3.  Also provides basic s3 helper"
  s.email = "dave@backupify.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "config/log4r.yml",
    "lib/logger_helper.rb",
    "lib/s3/storage_backed_attribute.rb",
    "lib/storage_backed_attributes.rb",
    "lib/test_helpers/storage_backed_test_helper.rb",
    "storage_backed_attributes.gemspec",
    "test/factories/data.rb",
    "test/factories/services.rb",
    "test/helper.rb",
    "test/lib/mock_cassandra_datum.rb",
    "test/lib/service.rb",
    "test/lib/storage_backed_datum.rb",
    "test/unit/s3/storage_backed_attribute_test.rb",
    "test/unit/storage_backed_attributes_test.rb"
  ]
  s.homepage = "http://github.com/backupify/storage_backed_attributes"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Allows models to add attributes which have content backed by s3.  Also provides basic s3 helper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_runtime_dependency(%q<exception_helper>, [">= 0"])
      s.add_runtime_dependency(%q<filter_io>, [">= 0"])
      s.add_runtime_dependency(%q<s3_helper>, [">= 0"])
      s.add_runtime_dependency(%q<excon>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<exception_helper>, [">= 0"])
      s.add_dependency(%q<filter_io>, [">= 0"])
      s.add_dependency(%q<s3_helper>, [">= 0"])
      s.add_dependency(%q<excon>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<exception_helper>, [">= 0"])
    s.add_dependency(%q<filter_io>, [">= 0"])
    s.add_dependency(%q<s3_helper>, [">= 0"])
    s.add_dependency(%q<excon>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

